language: node_js
node_js:
- '0.10'
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/df4440290bd89d941fb4
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
addons:
  sauce_connect:
    username: ampersandjs-ci
    access_key:
      secure: "oDMd8KDCmo1yWdlYqY0yzPk68EzT+jgR4i4AHMGrrcBwGHyNNzGg+bPZQZ4xQd4UqqB/is0ekq7g0XMOtj3BCLZg4kK3+bXHKAGL2Qr6tljpBA7tdl7b1C7OBTFDCtau0zXsVQ3iRudyiJGmpV1RCLdPvy2pe+Jr4bWwXeFONAI="

script: npm run test-ci
