language: node_js
node_js:
- '0.10'
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/df4440290bd89d941fb4
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
addons:
  sauce_connect:
    username: ampersandjs-ci
    access_key: secure: "oOuA29CKG77Lox3UguS4iXafAAlHZz0NEb1naCgnb63qWKRXxwRdjsKxOwWnFHaTL3SgQ1H9EVht5g8jygjsPIGJ5eb3yfFLHPEFp/Hk6D6x6Fp3OU4mxEYudhREb8u12r8lH3GQZzcQgLDMJRaN6IdY+3OOpiKYDdfL/BHIL0Y="      
script: npm run test-ci
